import { FETCH_PRODUCT_DETAILS_SUCCESS, FETCH_PRODUCT_DETAILS_FAILURE, FETCH_PRODUCT_DETAILS_REQUEST, UPDATE_PRODUCT_DETAILS_REQUEST, UPDATE_PRODUCT_DETAILS_FAILURE, UPDATE_PRODUCT_DETAILS_SUCCESS } from "../constant";

