export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const  LOGOUT_REQUEST = "LOGOUT_REQUEST"

export const MAC_ADDRESS = "1CC10CAD6226"
export const BASIC_URL = "https://i-stage.mkwms.dev/api/v1"


export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE"

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_OPTION = "SET_SEARCH_OPTION";
export const SET_FILTER_OPTION = "SET_FILTER_OPTION";
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SORT_OPTION = "SET_SORT_OPTION";
export const SET_SORT_ORDER = "SET_SORT_ORDER";


export const FETCH_FILTER_OPTIONS_REQUEST = "FETCH_FILTER_OPTIONS_REQUEST"
export const FETCH_FILTER_OPTIONS_SUCCESS = "FETCH_FILTER_OPTIONS_SUCCESS"
export const FETCH_FILTER_OPTIONS_FAILURE = "FETCH_FILTER_OPTIONS_FAILURE"
export const UPDATE_FILTER = "UPDATE_FILTER"
export const RESET_FILTER = "RESET_FILTER"
export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";

export const FETCH_SELECT_OPTIONS_REQUEST = "FETCH_SELECT_OPTIONS_REQUEST"
export const FETCH_SELECT_OPTIONS_SUCCESS = "FETCH_SELECT_OPTIONS_SUCCESS"
export const FETCH_SELECT_OPTIONS_FAILURE = "FETCH_SELECT_OPTIONS_FAILURE"

export const UPDATE_FIELD = "UPDATE_FIELD";
export const RESET_FORM = "RESET_FORM";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const  SUBMIT_FORM_REQUEST = "SUBMIT_FORM_REQUEST"
export const  SUBMIT_FORM_SUCCESS = "SUBMIT_FORM_SUCCESS"
export const  SUBMIT_FORM_FAILURE = "SUBMIT_FORM_FAILURE"
export const SET_SELECTED_SECTION = "SET_SELECTED_SECTION"
export const SET_FORM_DATA = "SET_FORM_DATA"


export const FETCH_PRODUCT_DETAILS_REQUEST = 'FETCH_PRODUCT_DETAILS_REQUEST';
export const FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETAILS_SUCCESS';
export const FETCH_PRODUCT_DETAILS_FAILURE = 'FETCH_PRODUCT_DETAILS_FAILURE';

export const UPDATE_PRODUCT_DETAILS_REQUEST = 'UPDATE_PRODUCT_DETAILS_REQUEST';
export const UPDATE_PRODUCT_DETAILS_SUCCESS = 'UPDATE_PRODUCT_DETAILS_SUCCESS';
export const UPDATE_PRODUCT_DETAILS_FAILURE = 'UPDATE_PRODUCT_DETAILS_FAILURE';

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"